/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package puissance4_batard_moore;
/**
 *
 * @author Administrateur
 */
public class interface_graph extends javax.swing.JFrame {
    private PlateauDeJeu plateauBis = new PlateauDeJeu();

    /**
     * Creates new form interface_graph
     */
    public interface_graph() {
        initComponents();
        panneauInformationsJoueurs.setVisible(false);
        panneauInformationsPartie.setVisible(false);
        for (int i = 5; i >= 0; i--) {
            for (int j = 0; j < 7; j++) {
                CelluleDeGrilleGraphique cellGraph = new CelluleDeGrilleGraphique(plateauBis.retournerCase(i,j)); // comment prendre les cellulessans demarrer une partie? 
                panneauGrille.add(cellGraph);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneauGrille = new javax.swing.JPanel();
        panneauInformationsPartie = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        infoJoueurCourant = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoMessage = new javax.swing.JTextArea();
        panneauInformationsJoueurs = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        infoJ1Nom = new javax.swing.JLabel();
        infoJ1Couleur = new javax.swing.JLabel();
        infoJ1Desintegrateurs = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        infoJ2Nom = new javax.swing.JLabel();
        infoJ2Couleur = new javax.swing.JLabel();
        infoJ2Desintegrateurs = new javax.swing.JLabel();
        panneauCreationPartie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom_joueur_2 = new javax.swing.JTextField();
        nom_joueur_1 = new javax.swing.JTextField();
        btn_start = new javax.swing.JButton();
        btn_col_0 = new javax.swing.JButton();
        btn_col_1 = new javax.swing.JButton();
        btn_col_2 = new javax.swing.JButton();
        btn_col_3 = new javax.swing.JButton();
        btn_col_4 = new javax.swing.JButton();
        btn_col_5 = new javax.swing.JButton();
        btn_col_6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneauGrille.setBackground(new java.awt.Color(102, 255, 102));
        panneauGrille.setLayout(new java.awt.GridLayout(6, 7));
        getContentPane().add(panneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 672, 576));

        panneauInformationsPartie.setBackground(new java.awt.Color(255, 255, 102));
        panneauInformationsPartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setText("Infos Jeu");
        panneauInformationsPartie.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 140, 40));

        infoJoueurCourant.setText("leJoueurCourant");
        panneauInformationsPartie.add(infoJoueurCourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 100, 30));

        jLabel9.setText("joueur Courant:");
        panneauInformationsPartie.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 30));

        infoMessage.setColumns(20);
        infoMessage.setRows(5);
        jScrollPane1.setViewportView(infoMessage);

        panneauInformationsPartie.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 70));

        getContentPane().add(panneauInformationsPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, 290, 140));

        panneauInformationsJoueurs.setBackground(new java.awt.Color(255, 51, 255));
        panneauInformationsJoueurs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("Infos Joueurs");
        panneauInformationsJoueurs.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, 40));

        jLabel4.setText("desintegrateurs :");
        panneauInformationsJoueurs.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel5.setText("joueur 1 :");
        panneauInformationsJoueurs.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 60, 30));

        jLabel6.setText("couleur :");
        panneauInformationsJoueurs.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, -1));

        infoJ1Nom.setText("nomDuJoueur1");
        panneauInformationsJoueurs.add(infoJ1Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        infoJ1Couleur.setText("Couleur1");
        panneauInformationsJoueurs.add(infoJ1Couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        infoJ1Desintegrateurs.setText("nbDesinte1");
        panneauInformationsJoueurs.add(infoJ1Desintegrateurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        panneauInformationsJoueurs.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 270, -1));

        jLabel10.setText("desintegrateurs :");
        panneauInformationsJoueurs.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel11.setText("joueur 1 :");
        panneauInformationsJoueurs.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 60, 30));

        jLabel12.setText("couleur :");
        panneauInformationsJoueurs.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 50, -1));

        infoJ2Nom.setText("nomDuJoueur2");
        panneauInformationsJoueurs.add(infoJ2Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        infoJ2Couleur.setText("Couleur2");
        panneauInformationsJoueurs.add(infoJ2Couleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        infoJ2Desintegrateurs.setText("nbDesinte2");
        panneauInformationsJoueurs.add(infoJ2Desintegrateurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        getContentPane().add(panneauInformationsJoueurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 290, 280));

        panneauCreationPartie.setBackground(new java.awt.Color(102, 255, 255));
        panneauCreationPartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom joueur 2: ");
        panneauCreationPartie.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel2.setText("Nom joueur 1: ");
        panneauCreationPartie.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        nom_joueur_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_joueur_2ActionPerformed(evt);
            }
        });
        panneauCreationPartie.add(nom_joueur_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 90, -1));
        panneauCreationPartie.add(nom_joueur_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 90, -1));

        btn_start.setText("Démarrer Partie");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        panneauCreationPartie.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        getContentPane().add(panneauCreationPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 290, 100));

        btn_col_0.setText("1");
        getContentPane().add(btn_col_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        btn_col_1.setText("2");
        btn_col_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 30, -1, -1));

        btn_col_2.setText("3");
        getContentPane().add(btn_col_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 30, -1, -1));

        btn_col_3.setText("4");
        btn_col_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 30, -1, -1));

        btn_col_4.setText("5");
        getContentPane().add(btn_col_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 30, -1, -1));

        btn_col_5.setText("6");
        getContentPane().add(btn_col_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        btn_col_6.setText("7");
        btn_col_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_col_6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_col_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 30, -1, -1));

        setBounds(0, 0, 1030, 687);
    }// </editor-fold>//GEN-END:initComponents

    private void nom_joueur_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_joueur_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_joueur_2ActionPerformed

    private void btn_col_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_col_6ActionPerformed

    private void btn_col_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_col_1ActionPerformed

    private void btn_col_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_col_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_col_3ActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        // TODO add your handling code here:
        String joueur1 = nom_joueur_1.getText();
        String joueur2 = nom_joueur_2.getText();
        Partie game = new Partie(joueur1, joueur2);
        game.initialiserPartie();
        infoJ1Nom.setText(joueur1);
        infoJ2Nom.setText(joueur2);
        panneauInformationsJoueurs.setVisible(true);
        panneauInformationsPartie.setVisible(true);
        panneauGrille.removeAll();
        for (int i = 5; i >= 0; i--) {
            for (int j = 0; j < 7; j++) {
                CelluleDeGrilleGraphique cellGraph = new CelluleDeGrilleGraphique(game.getPlateau().retournerCase(i,j)); // comment prendre les cellulessans demarrer une partie? 
                panneauGrille.add(cellGraph);
            }
        }
        panneauGrille.repaint();
    }//GEN-LAST:event_btn_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface_graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface_graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface_graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface_graph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interface_graph().setVisible(true);
            }
        });
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_col_0;
    private javax.swing.JButton btn_col_1;
    private javax.swing.JButton btn_col_2;
    private javax.swing.JButton btn_col_3;
    private javax.swing.JButton btn_col_4;
    private javax.swing.JButton btn_col_5;
    private javax.swing.JButton btn_col_6;
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel infoJ1Couleur;
    private javax.swing.JLabel infoJ1Desintegrateurs;
    private javax.swing.JLabel infoJ1Nom;
    private javax.swing.JLabel infoJ2Couleur;
    private javax.swing.JLabel infoJ2Desintegrateurs;
    private javax.swing.JLabel infoJ2Nom;
    private javax.swing.JLabel infoJoueurCourant;
    private javax.swing.JTextArea infoMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nom_joueur_1;
    private javax.swing.JTextField nom_joueur_2;
    private javax.swing.JPanel panneauCreationPartie;
    private javax.swing.JPanel panneauGrille;
    private javax.swing.JPanel panneauInformationsJoueurs;
    private javax.swing.JPanel panneauInformationsPartie;
    // End of variables declaration//GEN-END:variables
}
